"""
Django settings for homework_tracker project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Load environment variables from the .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'your-default-secret-key')  # Set default if not in .env

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Allowable hosts for production/deployment
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',  # Custom user app
    'homework',  # Homework-related app
    'games',  # Games-related app
]

# Ensure ROOT_URLCONF is set correctly
ROOT_URLCONF = 'homework_tracker.urls'

# Middleware configuration
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Ensure this is correctly placed
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Ensure correct order
    'django.contrib.messages.middleware.MessageMiddleware',  # Ensure correct order
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Template configuration for admin
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # You can add template directories here if you want custom templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application
WSGI_APPLICATION = 'homework_tracker.wsgi.application'

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'  # URL for serving static files
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Custom static directory inside the project
]

# Database configuration
DATABASE_URL = os.getenv('DATABASE_URL', 'sqlite:///' + str(BASE_DIR / 'db.sqlite3'))  # Optionally use DATABASE_URL from .env
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Default database engine
        'NAME': BASE_DIR / 'db.sqlite3',  # Override this if DATABASE_URL is used
    }
}

# User model configuration
AUTH_USER_MODEL = os.getenv('AUTH_USER_MODEL', 'users.User')  # Custom user model (from users app)
