# Generated by Django 5.2 on 2025-04-11 13:03

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_initial'),  # This is the last migration number
    ]

    operations = []
