# Generated by Django 5.2 on 2025-04-11 13:03

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_fake_migration'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS homework_childprogress;', reverse_sql=''),
        migrations.RunSQL('DROP TABLE IF EXISTS homework_dailyhomework;', reverse_sql=''),
        migrations.RunSQL('DROP TABLE IF EXISTS homework_homeworktask;', reverse_sql=''),
    ]
