# Generated by Django 5.2 on 2025-04-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_fake_migration'),
        ('homework', '0004_reset_schema'),
    ]

    operations = [
    ]
